name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
title: "[Feature]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: Please describe the problem you're trying to solve
      placeholder: I'm frustrated when...
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: What should the app do?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context or screenshots
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
          required: true

